const bcrypt = require('bcryptjs');
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();
const now = new Date('2026-07-07T00:00:00.000Z');
const PASSWORD = process.env.DEMO_PASSWORD || 'Password123!';

const roles = [
  { id: '64a000000000000000000001', roleName: 'Admin' },
  { id: '64a000000000000000000002', roleName: 'Teacher' },
  { id: '64a000000000000000000003', roleName: 'Student' },
];

const users = [
  { id: '64b000000000000000000001', email: 'admin@example.com', fullName: 'Demo Admin', role: 'Admin' },
  { id: '64b000000000000000000002', email: 'teacher@example.com', fullName: 'Primary Demo Teacher', role: 'Teacher' },
  { id: '64b000000000000000000003', email: 'student@example.com', fullName: 'Primary Demo Student', role: 'Student' },
  ...Array.from({ length: 5 }, (_, index) => ({
    id: `64b00000000000000000001${index + 1}`,
    email: `teacher${index + 1}@example.com`,
    fullName: `Demo Teacher ${index + 1}`,
    role: 'Teacher',
  })),
  ...Array.from({ length: 14 }, (_, index) => ({
    id: `64b0000000000000000001${(index + 1).toString(16).padStart(2, '0')}`,
    email: `student${index + 1}@example.com`,
    fullName: `Demo Student ${index + 1}`,
    role: 'Student',
  })),
];

const classRows = [
  { id: '64c000000000000000000001', name: 'MMA301 Analytics Foundations', classCode: 'LMS101', teacherId: users[3].id },
  { id: '64c000000000000000000002', name: 'Backend Systems for LMS', classCode: 'LMS102', teacherId: users[4].id },
  { id: '64c000000000000000000003', name: 'Mobile Learning Experience', classCode: 'LMS103', teacherId: users[5].id },
  { id: '64c000000000000000000004', name: 'Data Engineering for Education', classCode: 'LMS104', teacherId: users[6].id },
  { id: '64c000000000000000000005', name: 'Assessment and Feedback', classCode: 'LMS105', teacherId: users[7].id },
];

const numberedStudents = users.filter((user) => user.email.startsWith('student'));

async function resetDemoData() {
  const classIds = classRows.map((row) => row.id);
  const userIds = users.map((user) => user.id);
  const roleIds = roles.map((role) => role.id);

  await prisma.$transaction([
    prisma.privateNote.deleteMany({ where: { id: { startsWith: '65d' } } }),
    prisma.grade.deleteMany({ where: { id: { startsWith: '65c' } } }),
    prisma.submissionFile.deleteMany({ where: { id: { startsWith: '65b' } } }),
    prisma.submission.deleteMany({ where: { id: { startsWith: '65a' } } }),
    prisma.exercise.deleteMany({ where: { id: { startsWith: '658' } } }),
    prisma.material.deleteMany({ where: { id: { startsWith: '659' } } }),
    prisma.topic.deleteMany({ where: { id: { startsWith: '657' } } }),
    prisma.postComment.deleteMany({ where: { id: { startsWith: '65f' } } }),
    prisma.classPost.deleteMany({ where: { id: { startsWith: '65e' } } }),
    prisma.attendanceLog.deleteMany({ where: { classId: { in: classIds } } }),
    prisma.alertLog.deleteMany({ where: { classId: { in: classIds } } }),
    prisma.alertThreshold.deleteMany({ where: { classId: { in: classIds } } }),
    prisma.studentPerformanceMetrics.deleteMany({ where: { classId: { in: classIds } } }),
    prisma.classSettings.deleteMany({ where: { classId: { in: classIds } } }),
    prisma.quizBank.deleteMany({ where: { classId: { in: classIds } } }),
    prisma.enrollment.deleteMany({ where: { classId: { in: classIds } } }),
    prisma.class.deleteMany({ where: { id: { in: classIds } } }),
    prisma.notification.deleteMany({ where: { userId: { in: userIds } } }),
    prisma.deviceToken.deleteMany({ where: { userId: { in: userIds } } }),
    prisma.systemLog.deleteMany({ where: { serviceName: 'seed-prisma' } }),
    prisma.userRole.deleteMany({ where: { userId: { in: userIds } } }),
    prisma.user.deleteMany({ where: { id: { in: userIds } } }),
    prisma.role.deleteMany({ where: { id: { in: roleIds } } }),
  ]);
}

async function seed() {
  await resetDemoData();

  const passwordHash = await bcrypt.hash(PASSWORD, 10);
  await prisma.role.createMany({ data: roles.map((role) => ({ ...role, createdAt: now })) });
  await prisma.user.createMany({
    data: users.map((user) => ({
      id: user.id,
      email: user.email,
      fullName: user.fullName,
      passwordHash,
      avatarURL: null,
      cognitoSub: `demo-${user.email}`,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    })),
  });
  await prisma.userRole.createMany({
    data: users.map((user, index) => ({
      id: `64d000000000000000000${(index + 1).toString(16).padStart(3, '0')}`,
      userId: user.id,
      roleId: roles.find((role) => role.roleName === user.role).id,
      createdAt: now,
    })),
  });

  await prisma.class.createMany({
    data: classRows.map((row) => ({
      id: row.id,
      name: row.name,
      description: 'Medium demo class generated by reset-dev seed.',
      classCode: row.classCode,
      teacherId: row.teacherId,
      status: 'active',
      createdAt: now,
      updatedAt: now,
    })),
  });

  for (const [classIndex, classRow] of classRows.entries()) {
    const classStudents = numberedStudents.slice(classIndex * 2, classIndex * 2 + 6);

    await prisma.classSettings.create({ data: { id: `65000000000000000000000${classIndex + 1}`, classId: classRow.id, allowStudentPosts: true, allowStudentComments: true, theme: 'default', createdAt: now, updatedAt: now } });
    await prisma.alertThreshold.createMany({
      data: [
        { id: `65100000000000000000000${classIndex + 1}`, classId: classRow.id, metricType: 'attendance', thresholdValue: 75, severity: 'medium', createdAt: now, updatedAt: now },
        { id: `65200000000000000000000${classIndex + 1}`, classId: classRow.id, metricType: 'grades', thresholdValue: 60, severity: 'high', createdAt: now, updatedAt: now },
        { id: `65300000000000000000000${classIndex + 1}`, classId: classRow.id, metricType: 'submissions', thresholdValue: 80, severity: 'low', createdAt: now, updatedAt: now },
      ],
    });

    await prisma.enrollment.createMany({
      data: classStudents.map((student, studentIndex) => ({
        id: `65400000000000000000${classIndex + 1}${(studentIndex + 1).toString().padStart(3, '0')}`,
        classId: classRow.id,
        studentId: student.id,
        status: 'enrolled',
        enrolledAt: now,
        createdAt: now,
        updatedAt: now,
      })),
    });
    await prisma.attendanceLog.createMany({
      data: classStudents.map((student, studentIndex) => ({
        id: `65500000000000000000${classIndex + 1}${(studentIndex + 1).toString().padStart(3, '0')}`,
        classId: classRow.id,
        studentId: student.id,
        date: now,
        status: studentIndex % 5 === 0 ? 'late' : 'present',
        recordedBy: classRow.teacherId,
        createdAt: now,
        updatedAt: now,
      })),
    });
    await prisma.studentPerformanceMetrics.createMany({
      data: classStudents.map((student, studentIndex) => {
        const averageGrade = 72 + studentIndex * 3;
        return {
          id: `65600000000000000000${classIndex + 1}${(studentIndex + 1).toString().padStart(3, '0')}`,
          classId: classRow.id,
          studentId: student.id,
          attendanceRate: 82 + studentIndex,
          assignmentCompletionRate: 78 + studentIndex,
          averageGrade,
          currentAverage: averageGrade,
          missingCount: studentIndex % 3,
          riskLevel: studentIndex > 4 ? 'Warning' : 'Good',
          lastUpdated: now,
          createdAt: now,
          updatedAt: now,
        };
      }),
    });

    const topicRows = [1, 2].map((topicNumber) => ({
      id: `65700000000000000000${classIndex + 1}00${topicNumber}`,
      classId: classRow.id,
      title: topicNumber === 1 ? 'Getting Started' : 'Applied Practice',
      description: `Seeded topic ${topicNumber}`,
      order: topicNumber,
    }));
    await prisma.topic.createMany({ data: topicRows.map((topic) => ({ ...topic, createdAt: now, updatedAt: now })) });

    for (const [topicIndex, topic] of topicRows.entries()) {
      const exerciseId = `65800000000000000000${classIndex + 1}00${topicIndex + 1}`;
      await prisma.material.create({ data: { id: `65900000000000000000${classIndex + 1}00${topicIndex + 1}`, topicId: topic.id, title: `Lecture Notes ${topicIndex + 1}`, description: 'Seeded PDF material', fileUrl: `s3://lms-uploads/materials/${classRow.classCode}-${topicIndex + 1}.pdf`, fileType: 'pdf', uploadedBy: classRow.teacherId, createdAt: now, updatedAt: now } });
      await prisma.exercise.create({ data: { id: exerciseId, topicId: topic.id, title: `Assignment ${topicIndex + 1}`, description: 'Seeded assignment', dueDate: new Date(now.getTime() + (topicIndex + 7) * 24 * 60 * 60 * 1000), maxPoints: 100, createdBy: classRow.teacherId, createdAt: now, updatedAt: now } });

      if (classIndex === 0 && topicIndex === 0) {
        for (const [studentIndex, student] of classStudents.entries()) {
          const submissionId = `65a00000000000000000000${studentIndex + 1}`;
          await prisma.submission.create({ data: { id: submissionId, exerciseId, studentId: student.id, submittedAt: now, status: 'graded', points: 70 + studentIndex * 4, feedback: 'Seeded feedback', createdAt: now, updatedAt: now } });
          await prisma.submissionFile.create({ data: { id: `65b00000000000000000000${studentIndex + 1}`, submissionId, fileUrl: `s3://lms-uploads/submissions/${student.id}.pdf`, fileName: `${student.id}-assignment.pdf`, fileSize: 2048 + studentIndex, uploadedAt: now, createdAt: now, updatedAt: now } });
          await prisma.grade.create({ data: { id: `65c00000000000000000000${studentIndex + 1}`, submissionId, gradedBy: classRow.teacherId, points: 70 + studentIndex * 4, feedback: 'Good progress.', gradedAt: now, createdAt: now, updatedAt: now } });
          await prisma.privateNote.create({ data: { id: `65d00000000000000000000${studentIndex + 1}`, submissionId, senderId: classRow.teacherId, receiverId: student.id, content: 'Private seeded note for follow-up.', createdAt: now, updatedAt: now } });
        }
      }
    }

    const postId = `65e00000000000000000000${classIndex + 1}`;
    await prisma.classPost.create({ data: { id: postId, classId: classRow.id, authorId: classRow.teacherId, content: 'Welcome to the seeded demo class.', attachmentUrls: [], createdAt: now, updatedAt: now } });
    await prisma.postComment.create({ data: { id: `65f00000000000000000000${classIndex + 1}`, postId, authorId: classStudents[0].id, content: 'Thank you, teacher!', createdAt: now, updatedAt: now } });
    await prisma.quizBank.create({ data: { id: `66000000000000000000000${classIndex + 1}`, classId: classRow.id, title: 'Demo Quiz Bank', questions: [{ prompt: 'What is LMS?', answer: 'Learning Management System' }], createdBy: classRow.teacherId, createdAt: now, updatedAt: now } });
  }

  await prisma.notification.createMany({ data: numberedStudents.slice(0, 8).map((student, index) => ({ id: `66100000000000000000000${index + 1}`, userId: student.id, title: 'Demo notification', content: `Seeded notification ${index + 1}`, isRead: false, type: 'general', createdAt: now, updatedAt: now })) });
  await prisma.deviceToken.createMany({ data: numberedStudents.slice(0, 3).map((student, index) => ({ id: `66200000000000000000000${index + 1}`, userId: student.id, token: `demo-device-token-${index + 1}`, deviceType: ['web', 'ios', 'android'][index], createdAt: now, updatedAt: now })) });
  await prisma.alertLog.create({ data: { id: '663000000000000000000001', classId: classRows[0].id, studentId: numberedStudents[0].id, alertType: 'grades', message: 'Seeded grade alert', severity: 'medium', status: 'unread', createdAt: now, updatedAt: now } });
  await prisma.systemLog.create({ data: { id: '664000000000000000000001', serviceName: 'seed-prisma', level: 'info', message: 'Seeded PostgreSQL full demo data', metadata: { mode: 'reset-dev' }, timestamp: now, createdAt: now, updatedAt: now } });

  console.log('Seeded PostgreSQL auth and core demo data.');
}

seed()
  .catch((error) => {
    console.error('PostgreSQL seed failed:', error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
